### ISSUE TITLE
Rdoc @param not supported

### ISSUE THREAD

**Issue by christi-stripe** [skatkov/rdoc-markdown#39] opened 2023-05-31 10:53 UTC
Given this example:

```ruby
    # This is the mymethod comment
    #
    # @param [Integer] anint This is an integer
    # @param [String] astring This is a string
    #
    def self.mymethod(anint, astring)
      # ...
    end
```

the following markdown is generated:

```md
 ### mymethod(anint, astring) [](#method-c-mymethod4)
 This is the mymethod comment

@param [Integer] anint This is an integer @param [String] astring This is a string
```

which displays as follows:

---

 ### mymethod(anint, astring) [](#method-c-mymethod4)
 This is the mymethod comment

@param [Integer] anint This is an integer @param [String] astring This is a string

---

This uses the Rdoc syntax for `@param` as described [here](https://devhints.io/rdoc) which includes the text in the markdown but does not format it properly.

I would have expected something like the following:

```md
 ### mymethod(anint, astring) [](#method-c-mymethod4)
 This is the mymethod comment

 #### Parameters
| Name | Type | Description |
| ------ | ----- | ----------- |
| anint | Integer | This is an integer |
| astring | String | This is a string |
```

which displays as follows:

---
 ### mymethod(anint, astring) [](#method-c-mymethod4)
 This is the mymethod comment

 #### Parameters
| Name | Type | Description |
| ------ | ----- | ----------- |
| anint | Integer | This is an integer |
| astring | String | This is a string |
---

**Comment by skatkov** [comment] 2023-10-15 21:30
Thanks again for raising it and linking to devhints cheatsheet. 

But it seems, that there might be an issue with devhints. If you check [rdoc markup](http://docs.seattlerb.org/rdoc/RDoc/Markup.html), it doesn't list @param as a supported syntax and uses `:arg:` or `:args: instead.

But this parameters [is supported in yard](https://www.rubydoc.info/gems/yard/file/docs/Tags.md#param). 

It's easy to confuse these two, but it appears that this is not a bug.

I'm closing this, but please, feel free to reopen if I got anything wrong here.

**Closed** 2023-10-15 21:33 UTC
